/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-validation:2.7.5")
    implementation("org.springframework.boot:spring-boot-starter-web:2.7.5")
    implementation("org.springframework.boot:spring-boot-starter-actuator:2.7.5")
    implementation("org.springframework.boot:spring-boot-starter-data-jpa:2.7.5")
    implementation("org.modelmapper:modelmapper:3.1.0")
    implementation("org.springdoc:springdoc-openapi-ui:1.6.9")
    implementation("org.springframework.boot:spring-boot-configuration-processor:2.7.5")
//    implementation("com.github.javafaker:javafaker:1.0.2")
    implementation("org.springframework.boot:spring-boot-starter-security:2.7.5")
    implementation("org.springframework.security:spring-security-web:5.7.5")
    implementation("org.springframework.security:spring-security-config:5.7.5")
    implementation("org.springframework.security:spring-security-taglibs:5.7.5")
    implementation("org.springframework.boot:spring-boot-devtools:2.7.5")
    implementation("com.auth0:java-jwt:4.0.0")
    implementation("org.springframework.boot:spring-boot-starter-mail:2.7.5")
    runtimeOnly("org.postgresql:postgresql:42.3.6")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.7.5")
    compileOnly("org.projectlombok:lombok:1.18.24")
    annotationProcessor ("org.projectlombok:lombok:1.18.24")
}

group = "dev.ispiroglu"
version = "0.0.1-SNAPSHOT"
description = "job-adverty-system"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
